### Create User
POST  http://localhost:3000/user
Content-Type: application/json

{
        "username": "demo8",
        "password": "demo8"
}
    
### Update User
PUT http://localhost:3000/user/5
Content-Type: application/json

{
    "username": "demo5",
    "password": "newpassword"
}

### Delete User
DELETE http://localhost:3000/user/4

### Search User
GET http://localhost:3000/user/search?q=d
Content-Type: application/json
